# Статический редизайн: https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
  publish = "docs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
